const SERVER_EXCEPTION = 'SERVER_EXCEPTION';
const DB_LOG_SUCCESS = 'DB_LOG_SUCCESS';
const DB_LOG_FAIL = 'DB_LOG_FAIL';
const DB_UPDATE_SUCCESS = 'DB_UPDATE_SUCCESS';
const DB_UPDATE_FAIL = 'DB_UPDATE_FAIL';
const RAVE_PAY_FAIL = 'RAVE_PAY_FAIL';
const RAVE_VERIFY_FAIL = 'RAVE_VERIFY_FAIL';
const RAVE_VERIFY_TOKEN_FAIL = 'RAVE_VERIFY_TOKEN_FAIL';
const DB_LOG_PAYMENT_SUCCESS = 'DB_LOG_PAYMENT_SUCCESS';
const DB_LOG_PAYMENT_FAIL = 'DB_LOG_PAYMENT_FAIL';
const DB_FETCH_VERIFY_FAIL = 'DB_FETCH_VERIFY_FAIL';
const DB_UPDATE_VERIFY_FAIL = 'DB_UPDATE_VERIFY_FAIL';
const WEBHOOK_UPDATE = 'WEBHOOK_UPDATE';
const ERROR_ROUTE = 'ERROR_ROUTE';

module.exports = {
  SERVER_EXCEPTION,
  DB_LOG_SUCCESS,
  DB_LOG_FAIL,
  DB_UPDATE_SUCCESS,
  DB_UPDATE_FAIL,
  RAVE_PAY_FAIL,
  RAVE_VERIFY_FAIL,
  RAVE_VERIFY_TOKEN_FAIL,
  DB_LOG_PAYMENT_SUCCESS,
  DB_LOG_PAYMENT_FAIL,
  DB_FETCH_VERIFY_FAIL,
  DB_UPDATE_VERIFY_FAIL,
  WEBHOOK_UPDATE,
  ERROR_ROUTE,
};
